name: master

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.26
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: splendor
        ports:
          - 3306:3306
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 3

      redis:
        image: redis:6
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}  


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.1'

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Set Redis password
        run: |
          pws
          ls 
          docker cp redis.conf redis6:/usr/local/etc/redis/redis.conf  
        env:
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}  

      - name: Start Redis
        run: docker exec redis6 redis-server /usr/local/etc/redis/redis.conf  


      - name: Alembic upgrade heads
        run: poetry run alembic -c alembic.ini upgrade heads

      - name: Poetry run pytest
        run: poetry run pytest