name: master

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.1'
          
      - name: Docker Compose Up
        run: docker-compose up -d

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Alembic upgrade heads
        run: poetry run alembic -c alembic.ini upgrade heads

      - name: Poetry run pytest
        run: poetry run pytest